<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-A66MK7D" failures="2" tests="2" name="Default test(failed)" time="0.565" errors="0" timestamp="2022-03-22T14:10:40 IST">
  <testcase classname="testNgXmlStudy.Fail_class" name="b" time="0.516">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNgXmlStudy.Fail_class.b() didn&amp;apos;t finish within the time-out 500">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNgXmlStudy.Fail_class.b() didn't finish within the time-out 500
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- b -->
  <testcase classname="testNgXmlStudy.Fail_class" name="c" time="0.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNgXmlStudy.Fail_class.c(Fail_class.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- c -->
  <testcase classname="testNgXmlStudy.Fail_class" name="a" time="0.0">
    <ignored/>
  </testcase> <!-- a -->
  <testcase classname="testNgXmlStudy.Fail_class" name="d" time="0.0">
    <ignored/>
  </testcase> <!-- d -->
</testsuite> <!-- Default test(failed) -->
